query attachmentsConnection($organizationId: ID!, $folderId: ID, $trashed: Boolean, $term: String, $sortBy: AttachmentSortByEnum, $sortType: SortTypeEnum, $after: String, $before: String, $first: Int, $last: Int){
    attachmentsConnection(organizationId: $organizationId, folderId: $folderId, trashed: $trashed, term: $term, sortBy: $sortBy, sortType: $sortType, after: $after, before: $before, first: $first, last: $last){
        edges{
            cursor
            node{
                byteSize
                collectionsCount
                contentType
                createdAt
                createdBy{
                    avatarUrl
                    firstName
                    lastName
                }
                downloadUrl
                favoriteId
                fileType
                hasChildren
                id
                isFavored
                meta{
                    pageCount
                    slideCount
                }
                name
                originalPath
                previewUrl
                thumbnailUrl
                updatedAt
                versionsCount
            }
        }
        nodes{
            byteSize
            collectionsCount
            contentType
            createdAt
            createdBy{
                avatarUrl
                firstName
                lastName
            }
            downloadUrl
            favoriteId
            fileType
            hasChildren
            id
            isFavored
            meta{
                pageCount
                slideCount
            }
            name
            originalPath
            previewUrl
            thumbnailUrl
            updatedAt
            versionsCount
        }
        pageInfo{
            endCursor
            hasNextPage
            hasPreviousPage
            startCursor
        }
    }
}