query attachmentShow($organizationId: ID!, $id: ID!){
    attachmentShow(organizationId: $organizationId, id: $id){
        byteSize
        collectionsCount
        contentType
        createdAt
        createdBy{
            avatarUrl
            firstName
            lastName
        }
        dimensions
        downloadUrl
        favoriteId
        id
        isFavored
        meta{
            pageCount
            slideCount
        }
        metadata{
            id
            namespace
            tagName
            value
            valueType
        }
        name
        previewUrl
        stats{
            downloadCount
            monthlyStats{
                date
                downloadCount
            }
        }
        tags{
            aiConfidence
            id
            instances{
                confidence
                height
                left
                top
                width
            }
            isAi
            name
        }
        thumbnailUrl
        updatedAt
        versions{
            attachmentId
            createdAt
            createdBy{
                avatarUrl
                firstName
                lastName
            }
            isLive
            name
            version
        }
    }
}