query commentsConnection($organizationId: ID!, $commentableId: ID!, $commentableType: CommentCommentableTypeEnum!, $after: String, $before: String, $first: Int, $last: Int){
    commentsConnection(organizationId: $organizationId, commentableId: $commentableId, commentableType: $commentableType, after: $after, before: $before, first: $first, last: $last){
        edges{
            cursor
            node{
                body
                children{
                    body
                    children{
                        body
                        createdAt
                        id
                        isEdited
                        updatedAt
                        user{
                            avatarUrl
                            firstName
                            id
                            lastName
                        }
                    }
                    createdAt
                    id
                    isEdited
                    updatedAt
                }
                createdAt
                id
                isEdited
                updatedAt
                user{
                    avatarUrl
                    firstName
                    id
                    lastName
                }
            }
        }
        nodes{
            body
            children{
                body
                createdAt
                id
                isEdited
                updatedAt
            }
            createdAt
            id
            isEdited
            updatedAt
            user{
                avatarUrl
                firstName
                id
                lastName
            }
        }
        pageInfo{
            endCursor
            hasNextPage
            hasPreviousPage
            startCursor
        }
    }
}