query credentialsList($organizationId: ID!, $archived: Boolean){
    credentialsList(organizationId: $organizationId, archived: $archived){
        archivedAt
        createdAt
        id
        name
        provider
        updatedAt
    }
}