query credentialAuthLink($organizationId: ID!, $name: String!, $provider: CredentialAuthLinkProviderEnum!){
    credentialAuthLink(organizationId: $organizationId, name: $name, provider: $provider){
        link
    }
}