query integrationSlackChannelsList($organizationId: ID!, $integrationId: ID!){
    integrationSlackChannelsList(organizationId: $organizationId, integrationId: $integrationId){
        id
        name
    }
}