query organizationMembersList($organizationId: ID!, $term: String){
    organizationMembersList(organizationId: $organizationId, term: $term){
        id
        invitationEmail
        invitedAt
        invitedBy{
            avatarUrl
            firstName
            id
            lastName
        }
        joinedAt
        roles{
            id
            name
        }
        state
        teams{
            id
            name
        }
        user{
            avatarUrl
            firstName
            id
            lastName
        }
    }
}