query permissionLookup($organizationId: ID!, $entities: [PermissionEntitiesInput!]!){
    permissionLookup(organizationId: $organizationId, entities: $entities){
        entityId
        entityType
        permissions{
            allowed
            permission
        }
    }
}