query placeholdersList($eventType: AutomationTriggerEventTypeEnum!){
    placeholdersList(eventType: $eventType){
        description
        key
        label
        namespace
        returnType
    }
}