query teamShow($after: String, $before: String, $first: Int, $last: Int, $organizationId: ID!, $id: ID!){
    teamShow(organizationId: $organizationId, id: $id){
        activityLogs(after: $after, before: $before, first: $first, last: $last){
            edges{
                cursor
                node{
                    action
                    createdAt
                    id
                    ip
                    user{
                        avatarUrl
                        firstName
                        id
                        isDeleted
                        lastName
                    }
                    userAgent
                }
            }
            nodes{
                action
                createdAt
                id
                ip
                user{
                    avatarUrl
                    firstName
                    id
                    isDeleted
                    lastName
                }
                userAgent
            }
            pageInfo{
                endCursor
                hasNextPage
                hasPreviousPage
                startCursor
            }
        }
        createdAt
        description
        id
        name
        roles{
            description
            id
            kind
            name
            permissions{
                createdAt
                group
                id
                permission
            }
        }
        teamMembers{
            createdAt
            id
            updatedAt
            user{
                avatarUrl
                firstName
                lastName
            }
        }
        updatedAt
    }
}